### ISSUE TITLE
JSONDecodeError in model evaluation

### ISSUE THREAD

**Issue by msushkov** [conversationai/conversationai-models#217]
Reproduced in https://github.com/conversationai/conversationai-models/blob/msushkov_eval2/model_evaluation/model_eval.ipynb

**Comment by fprost** [comment]
Could you point at the model that you are using? Is is tf_gru_attention or another one?

**Comment by fprost** [comment]
I am assuming here that you are using the code for tf_gru_attention in your branch.

So looking at your notebook, it seems that:
- the API is  reading correctly your test file
- Is converting correctly to TF-Records
- Calls a batch prediction in CMLE
- BUT is unable to read back the prediction files.

Looking at your CMLE prediction job, I see that it was not able to parse the input file (otherwise you would have an example count).

This issue should come from a mismatch between the real model signature (the .pb that you deployed on CMLE) and what you described (your `Model` instance).
In particular, you are saying that:
- input spec = 'coment_text'
- example key = 'comment_key' (ok defined in model_trainer.py)
- prediction key = 'toxicity/logistic'.
Whereas from your tf_gru_attention code (hence your .pb), I see that:
- example_key is 'tokens' (in common/base_model.py called my run.py)
- prediction_key is tfrecord_input/logistic (in tfrecord_input.py). This mismatch is also due that you are training on toxicity_2017 whereas the notebook handles by default civil_comments.

So short term change to get your code to work should be to update your notebook with the right signature. Let me know if you run into issues here.

Long term change should solve:
1- Help the user to realize when the model signature does not match the on of the .pb:
- Can we automatically detect the signature of a model deployed on CMLE? In this case, we would send error messages when creating the `Model` instance.
- Otherwise, send more explicit error message when prediction file is empty.
2- Update default value of the notebook to `tokens` (made incompatible by [this commit](https://github.com/conversationai/conversationai-models/commit/0dac3ef488097163c28519c1233fd1f44a91a42b))
3- write better documentation for the `Model` attributes.

@msushkov, do you think that these changes could help avoid similar problems in the future?
 If yes, I will create a feature request and work on it when I have time.

**Comment by msushkov** [comment]
Thanks @fprost! My mistake. These long-term changes would definitely make things easier, especially automatically detecting the model signature or at the very least an explicit message when the prediction file is empty (the JSONDecodeError seems confusing to debug).

**Comment by fprost** [comment]
This problem was solved by the two PR #225 and #226. 

In the future, this [feature request](https://github.com/conversationai/conversationai-models/issues/230) will also be useful.
